#!/usr/bin/env php
<?php

use Somecode\Framework\Console\Kernel;

define('BASE_PATH', dirname(__FILE__));

require_once BASE_PATH.'/vendor/autoload.php';

/** @var League\Container\Container $container */
$container = require BASE_PATH.'/config/services.php';

$kernel = $container->get(Kernel::class);

$status = $kernel->handle();

exit($status);
